sudo: False
language: python
python:
   - 2.7

before_install:
   - pip install coverage

install: "pip install -r REQUIREMENTS.txt"

script: coverage run run_tests.py

after_success:
   - coveralls

